### ISSUE TITLE
Can't read attributes For input string: "id"

### ISSUE THREAD

**Issue by MihailGershkovich** [ascendix/salesforce-jdbc#19]
Connection is successful, can see all tables, however if I try to check available columns I see:
`Can't read attributes For input string: "id"`

If I try to select any column from any table, I receive no results....
Misconfiguration on my side?

**Comment by tomstock1337** [comment]
I'm experiencing this as well.

**Comment by gmillerd** [comment]
> I'm experiencing this as well.

What program are you using the jdbc driver with? You might find the debug/error logging from it and produce the error message  and or stack. Something similar to the below. 

> `java.lang.NumberFormatException: For input string: "id"
> 	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
> 	at java.base/java.lang.Integer.parseInt(Unknown Source)
> 	at java.base/java.lang.Integer.<init>(Unknown Source)
> 	at com.ascendix.jdbc.salesforce.CachedResultSet$ColumnValueParser.parse(CachedResultSet.java:167)
> 	at com.ascendix.jdbc.salesforce.CachedResultSet$ColumnValueParser.parse(CachedResultSet.java:161)
> 	at com.ascendix.jdbc.salesforce.CachedResultSet.getInt(CachedResultSet.java:326)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getInt(JDBCResultSetImpl.java:486)
> 	at org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils.safeGetInt(JDBCUtils.java:110)
> 	at org.jkiss.dbeaver.ext.generic.model.GenericUtils.safeGetInt(GenericUtils.java:84)
> 	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:149)
> 	at org.jkiss.dbeaver.ext.generic.model.TableCache.fetchChild(TableCache.java:1)
> 	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.loadChildren(JDBCStructCache.java:129)
> 	at org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCStructCache.getChildren(JDBCStructCache.java:221)
> 	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:148)
> 	at org.jkiss.dbeaver.ext.generic.model.GenericTableBase.getAttributes(GenericTableBase.java:1)
> 	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$TableAnalysisRunner.getAllAttributes(GenerateSQLContributor.java:518)
> 	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$9.generateSQL(GenerateSQLContributor.java:703)
> 	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$9.generateSQL(GenerateSQLContributor.java:1)
> 	at org.jkiss.dbeaver.ui.editors.sql.generator.GenerateSQLContributor$SQLGenerator.run(GenerateSQLContributor.java:439)
> 	at org.jkiss.dbeaver.ui.UIUtils.lambda$14(UIUtils.java:1666)
> 	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:436)
> 	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:352)
> 	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2419)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
> 	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2417)
> 	at org.eclipse.ui.internal.progress.ProgressManager$RunnableWithStatus.run(ProgressManager.java:1095)
> 	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
> 	at org.eclipse.ui.internal.progress.ProgressManager.lambda$25(ProgressManager.java:974)
> 	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
> 	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:146)
> 	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4629)
> 	at org.eclipse.ui.internal.progress.ProgressManager.runInUI(ProgressManager.java:974)
> 	at org.jkiss.dbeaver.ui.UIUtils.runInUI(UIUtils.java:1665)
> 	at org.jkiss.dbeaver.ui.editors.sql.handlers.OpenObjectConsoleHandler.openConsole(OpenObjectConsoleHandler.java:92)
> 	at org.jkiss.dbeaver.ui.editors.sql.handlers.OpenObjectConsoleHandler.execute(OpenObjectConsoleHandler.java:82)
> 	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
> 	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:95)
> 	at jdk.internal.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
> 	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
> 	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
> 	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
> 	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
> 	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
> 	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
> 	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:229)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)`

**Comment by nextcrm-castellanfederico** [comment]
Same here

**Comment by andyherzberg** [comment]
Hi there. I get the same error. Did somebody of you solve it?

**Comment by Karlodun** [comment]
I moved over to simple-salesforce and use it to migrate data into a PostgreSQL database:
https://github.com/Karlodun/simlpe-salesforce-postgres
I'll put my code there in a couple of days
