### ISSUE TITLE
Build instructions for create jar with dependencies

### ISSUE THREAD

**Issue by mknashi** [ascendix/salesforce-jdbc#8]
Could you share the instructions to build the jar file with dependencies?

**Comment by gorchenok** [comment]
Hi @mknashi thank you that you are interested of this project. 
For creating single jar file with dependencies you just need build with next parameters
**mvn clean install -P single-jar**
Let me know if it help

**Comment by mknashi** [comment]
Thanks for the instructions. I built the new jar with dependencies. I tried using this driver in dbVisualizer, but getting following exceptions:

2019-03-06 20:26:06.706 WARN   316 [ExecutorRunner-pool-4-thread-5 - C.getValueAt] IndexOutOfBoundsException: row=0 column=0 rowCount=1 columnCount=0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.onseven.dbvis.K.B.C.getValueAt(Z:543)
	at com.jidesoft.grid.TableModelWrapperImpl.getValueAt(X:2718)
	at com.jidesoft.grid.DefaultTableModelWrapper.getValueAt(X:3546)
	at com.onseven.dbvis.db.O.?(Z:1638)
	at com.onseven.dbvis.db.O.?(Z:1908)
	at com.onseven.dbvis.db.I.L.?(Z:3400)
	at com.onseven.dbvis.db.I.L.?(Z:1139)
	at com.onseven.dbvis.db.I.L.?(Z:1492)
	at com.onseven.dbvis.db.I.H.?(Z:1849)
	at com.onseven.dbvis.db.I.K.?(Z:3063)
	at com.onseven.dbvis.db.I.D.?(Z:1756)
	at com.onseven.dbvis.K.C.Z.?(Z:2713)
	at com.onseven.dbvis.K.C.K.?(Z:1374)
	at com.onseven.dbvis.K.C.K.doInBackground(Z:1521)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

However, on DBeaver, I am able to connect to Salesforce but query results do not show in the results panel. It just shows the statistics.

Please let me know if anything else needs to be done.

**Comment by mknashi** [comment]
Could you let me know if the driver works with DBeaver of dbVisualizer?
